name: Rust

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: Build | Lint
        run: cargo clippy

  test:
    name: Test
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
    runs-on: windows-latest
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Test
        run: cargo test

  compile:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Build | Compile
        run: cargo build --release
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dijkstra
          path: target/release/Dijkstra.exe  # Replace with your actual project name
